### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by artch** [TooAngel/screeps#1]
You have these mandatory dependencies in your package.json:

```
{
    "grunt": "~0.4.5",
    "grunt-screeps": "1.2.0",
    "grunt-sync": "^0.6.2",
    "screeps-profiler": "^1.1.1"
  }
```

They are installed on every server when users install your bot via the Workshop or npm. I guess it is better to move them to `devDependencies` instead.

**Comment by TooAngel** [comment]
Thx, for the hint, the npm package has these dependencies already as devDependencies, will update the github repository shortly.

**Comment by TooAngel** [comment]
Done
