### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#100]
Hola! @Somotaw has created a [ZenHub](http://www.zenhub.com) account for the **TooAngel** organization. ZenHub is the only project management tool integrated natively in GitHub – created specifically for fast-moving, software-driven teams.

----

#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.com?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.

#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:

- Real-time, customizable task boards for GitHub issues;
- Multi-Repository burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- Time-saving shortcuts – like a quick repo switcher, a “Move issue” button, and much more.

### [Add ZenHub to GitHub](https://www.zenhub.com?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.com/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @Somotaw._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by TooAngel** [comment]
Had a quick look. Don't think it fits.
For progress tracking we could use github projects, I started one for minerals https://github.com/TooAngel/screeps/projects/1 which is similar.

Didn't look too much in reports maybe this is helpful, if you or someone wants to use it I'm fine.

I think we are not yet on the level that we need multiple states for multiple features. For me this is a fun project, I don't want to commit to do anything. E.g. autoattack 2 is lying around, current prefer to play with other stuff, so I don't mind. I guess most of the people who will contribute will do the same. For a company purpose with goal, deadlines, ... the project management is much more important.

If you like to try something, let's try it with github projects and see what we are missing and if we want to do stuff like that.

**Comment by Somotaw** [comment]
I can agree this project might not be big enough to need this, but I can see some advantages to using some of its features, will look into projects more and evaluate :)

**Comment by Somotaw** [comment]
As it is now, I cant really do much with projects, all it is is a list which I cant edit that links to issues or pull requests.
