### ISSUE TITLE
feature/Improve nextroomer source selection

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#105]
We need to have them select a second source if there are no empty spots on the first one :)
need to make them use containers if present. We might need to increase the work parts to empty sources quicker

**Comment by gsc89** [comment]
Can concour I have this problem right now and its really screwing the room speed. 

W84S1 ... incase its not still doing it when anyone looks:

![image](https://cloud.githubusercontent.com/assets/1032459/22865100/faa76268-f154-11e6-986e-76876215f8d0.png)

**Comment by TooAngel** [comment]
I think some improvements were implemented already.
