### ISSUE TITLE
Issues with sourcer logic

### ISSUE THREAD

**Issue by YourHuckleberry** [TooAngel/screeps#108]
Not sure what's going on, but the sourcer roles do not appear to be working as expected.  At one point, one of them was working as expected, then neither worked.  When they are not working (just sitting one square away from the source) they will constanly say 'R:-1 pre'.  (Source is hidden under the text bubble - the sourcer has never touched this source point in thousands of ticks).

![image](https://cloud.githubusercontent.com/assets/5511530/21755963/e2c2c4b2-d5e8-11e6-90c6-73c76583bf24.png)

**Comment by Somotaw** [comment]
is this after trying a delete Memory.rooms.'roomname' ?

**Comment by YourHuckleberry** [comment]
Tried your suggestion Somotaw, first try worked for about ten tics then reverted, but second clearing of the memory seems to have worked.  I'll take it as a win either way, thanks!

**Comment by Somotaw** [comment]
#124 Should fix this 👍

**Comment by TooAngel** [comment]
Is this issue fixed?

**Comment by Somotaw** [comment]
Current revision still has the problem in SOME rooms on private, those rooms acutually seem to reset pathing to a different version every once in a while borking stuff so I would say issue not fixed, maybe look at pathing instead of sourcer?

**Comment by Somotaw** [comment]
#160
