### ISSUE TITLE
Suggest adding Code Climate to status checks

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#115]
As above

**Comment by Somotaw** [comment]
You know so you can see the results without having to manually check page :D

**Comment by TooAngel** [comment]
Do I have to do something? Can you do it? Not exactly sure what it is, will see :-)

**Comment by Somotaw** [comment]
You have to in project settings :) you have circleCI added the same way :)

**Comment by Somotaw** [comment]
👍
