### ISSUE TITLE
Towers not being filled

### ISSUE THREAD

**Issue by Brutalbic** [TooAngel/screeps#12]
I've been running this script for a few days on my private server to study what it does. For the most part it's working fine for me, however the tower that has been built is not getting any resources put in it at all.

Edit: Adding to earlier, studying the memory that's been created, I can see that towerfiller is only called when the room is under attack, but the tower still has no energy after I was attacked, instead it used the energy to create 2 ranged attackers to defend the room

RCL is currently 4, so I'm expecting to see storagefiller once it's reached 5

Will see what I can do to get at least some energy in the tower to prepare for another attack

**Comment by TooAngel** [comment]
Thank you for testing and looking into this.

I also recognized that the tower near the storage is not filled properly. RCL < 5 should be done be the `harvester` creep. RCL >= 5 a `storagefiller` is placed next to the storage, link, tower, which should take care of filling the tower.

The plan for the `towerfiller` you mentioned is:
Next to the path to the exits a link and a tower is build, in case of an attack a `towerfiller` is spawned which will sit between both buildings and transfers energy from the link to the tower.
In the last update of the basebuilding the link and tower placement seems sometimes broken. So don't expect too much :-)

**Comment by Brutalbic** [comment]
Thanks,
After looking more into the comments you wrote in the different modules, I worked out the tower filler sits between the link and a tower as you have mentioned.

On another note, I decided to change my original room (also to replace the original spawn location to a location it preferred) it no longer builds ramparts around it.
Here is an example of the only room I am currently posessing
![image](https://cloud.githubusercontent.com/assets/24380545/20882365/b67eead0-bb34-11e6-8bcc-5e5201ee775f.png)

**Comment by TooAngel** [comment]
I would suggest to execute in the console: `delete Memory.rooms.ROOMNAME`
Which will restart the base and walls setup.

I introduce the ramparts around the spawn a couple of days ago, mainly to prevent the spawn (when it is set randomly) sitting within a wall and is not reachable. I called it misplacedSpawn, if the spawn is at the correct location no ramparts are needed.

**Comment by Brutalbic** [comment]
I'll give it a try in a couple of hours when I'm back and let you know what happens.

**Comment by TooAngel** [comment]
Btw. the misplacedSpawn is automatically rebuild at the correct location on RCL 4 and storage.store.energy > 20k

Usually you should be able to wipe the complete memory and eventually the system converges, I usually only do `delete Memory.rooms`

**Comment by Brutalbic** [comment]
Ah, I understand what you mean now. When I placed the spawn originally I could see it show the misplaced spawn, but it would constantly spam the console with misplaced spawn, even after all the ramparts were built.

I scoured through the memory and found what location it was planning to place the spawner, so I restarted that room and placed it in the first location it wanted to place a spawn in.

Room has reached RCL 5 and the tower now has 50% energy, storagefiller is standing between the storage (which is now empty) the tower, and the link.

Looks like it's all working fine after RCL reached 5. Though one thing to note is the vulnerable stage after being able to build the towers to having to place 405k energy in the RCL before the tower actually starts getting resources

**Comment by TooAngel** [comment]
I released a new version, where the tower should be filled by the harvester RCL < 4, too.
I'm not sure about RCL == 4, I have to check, I'm waiting for one of my rooms get to RCL 4 :-)

**Comment by Brutalbic** [comment]
Yeah, I wasn't able to check that, I only have access to one private server (it's not the best either) so testing is rather limited at the moment

**Comment by TooAngel** [comment]
:-) No worries, I happy about that feedback.

If you find anything what should be improved I'm happy about a comment or PR

**Comment by Brutalbic** [comment]
Sorry, the issue was fixed when you made that update a while ago, I can see it works now :)
