### ISSUE TITLE
feature/Reservers-add-respawn-on-death

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#121]
Anything else I need to do besides queue a new one on death and reset timer?

**Comment by TooAngel** [comment]
They should queue up replacements, already.

Or do you want to solve something different?

**Comment by Somotaw** [comment]
Respawning after death by invaders or hostiles :)

**Comment by Somotaw** [comment]
I guess preferrably we'd avoid that but it should be a simple fix if you want something releaseworthy ;)

**Comment by TooAngel** [comment]
I'm fine with that, had something like that in `brain_memory`, spawned too many reserver, removed it :-)

**Comment by Nevrdid** [comment]
Reservers spawn should work correctly as it should spawn them if you can reserve a new one when a creep come in an unreserved room but the problem come from the scout issue because a reserved room which 'die' is no more visited later and after 500 ticks, reserver no more try to go back in.

**Comment by Somotaw** [comment]
has this been fixed by the scout fix? It might?

**Comment by Somotaw** [comment]
feels like it
