### ISSUE TITLE
New rooms should activate safe mode when under attack

### ISSUE THREAD

**Issue by WhiteHalmos** [TooAngel/screeps#131]
A single enemy can wipe out a new room since currently there is no defense. Have to manually activate safe mode.

**Comment by TooAngel** [comment]
I think the save move is triggered if the room is active, if nothing noteworthy is constructed, why waste safe mode.

But this can surely be double checked and improved.
https://github.com/TooAngel/screeps/blob/master/src/prototype_room_my.js#L291

**Comment by WhiteHalmos** [comment]
True, defenders are spawned later so it's fine.
