### ISSUE TITLE
Extractors are moving back and fourth and not mining every tick? Intentional? In that case make them stand still? :)

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#156]

**Comment by TooAngel** [comment]
http://support.screeps.com/hc/en-us/articles/207715739-StructureExtractor

You can only harvest every 5 ticks

**Comment by Somotaw** [comment]
I know this, but moving them costs cpu.

**Comment by Somotaw** [comment]
What i meant was mining every tick they could.

**Comment by aceofaces** [comment]
One of the reasons to have them moving is for the times when the mineral/extractor location is right on a major path.

**Comment by Somotaw** [comment]
why not just edit the file with moving prios to move the extractor if its in path? :)

**Comment by Somotaw** [comment]
like we do with harvesters carrys etc

**Comment by Somotaw** [comment]
Same with the mineral worker when theres no work :)

**Comment by TooAngel** [comment]
Not sure if I can follow this, just to clear up the definitions:
extractor: The creep getting the energy out of the mineral/extractor. Should usually have it's position next to the extractor, shouldn't block anything
mineral: The creep distributin the mineral from terminal to labs. This one usually moves on well driven path and could block other creeps. So should move or should be moved by others.
While I guess, be moved by others costs more CPU.,

**Comment by Somotaw** [comment]
yes those are the definitions i've been using :)

**Comment by TooAngel** [comment]
:-) K, so I still can't follow.

**Comment by Somotaw** [comment]
Extractors move when they cant extract, costing us cpu, also they sometimes are at a position which they cant extract from when the extractor cooldown is finished.

**Comment by TooAngel** [comment]
Is it the 4 ticks cooldown or the no more mineral a couple of thousand ticks?

**Comment by Somotaw** [comment]
the small cd

**Comment by KBOPYM** [comment]
The thing is, when there is only one spot to mine from, extractor moves avay from mineral and can't mine next tick, then it could've been possible othervise

**Comment by mschultheiss83** [comment]
i have got more than one room were this would happen:
if miner would stand still, the mineral creep counld not fill/empty the labs...

maybe close?

**Comment by TooAngel** [comment]
Will close this here. I see some advantages of the moving like @mschultheiss83 while this could also solved with the room layout.

If we miss a tick on the mineral that wouldn't be so cool, but I'm still not sure.
