### ISSUE TITLE
Carrys getting stuck on room edges moving back and fourth? :)

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#157]

**Comment by Vanhal** [comment]
Seems to be happening with newroomers too.
![image](https://cloud.githubusercontent.com/assets/7526890/22510877/91ba639e-e88b-11e6-9b03-1a820751486e.png)

**Comment by gsc89** [comment]
I have seen this with my scouts and this was last night and then again this morning but not right now. I will see if I spot this again.

**Comment by Vanhal** [comment]
Seems to be when they are routing to the source:
![image](https://cloud.githubusercontent.com/assets/7526890/22514319/d98c75a8-e896-11e6-88bf-2858c4ff6532.png)

I've tried increasing the borderAvoid config value but it doesn't seem to help.

**Comment by Nevrdid** [comment]
any log ? can you display paths ? it can be an issue in moveByPathMy, in preMove or alot of other things if something happen wrong.
I propose you to add some debuging console.log starting from MoveByPathMy for see first what the nextroomers try to do and what they don't. I supose they use one moveTo(but which ? ^^) and so they try to avoid swamp and so they block themself as it no more use method for unstuck screeps. But need more informations for try to fix ^^'

**Comment by Vanhal** [comment]
No log output, I can display paths but there is none. So I dug into the code a bit like you suggested and it seems to be the base creep.moveTo that is causing the movement issue (possibly in relation to the routing).

I found if I set the creep to always use the path (removing the first if statement here: https://github.com/TooAngel/screeps/blob/master/src/prototype_creep_resources.js#L585) then it will go the correct way round. 

I suspect what is happening is that the regular moveTo command is routing outside of the room, then when the creep is outside the room it's meant to be in the custom routing sends it back to the other room and it just flip flops from there.....

**Comment by Nevrdid** [comment]
can you try to do the modifications i did here on creep_proto_ressources l514-532? : 
https://github.com/TooAngel/screeps/pull/186/files
i'm not sure if it can fix it as item should be already defined but better try:)

**Comment by Vanhal** [comment]
I actually already had those changes added to my codebase. Problem exists with or without them.

A potential solution is to create a new moveTo method that will only search for paths within the same room.
My temp solution was to just to remove the (this.room.controller.level < 3) of the if statement, it makes them go the long way round, but it's better than them just bouncing back and fourth at the top of the room.

**Comment by Nevrdid** [comment]
did you also try ` if ((Game.time % 2) && (this.ro...` ? the one in previous comment was wrong ^^'

**Comment by Vanhal** [comment]
With the (Game.time % 2) added the creeps just rock back and fourth in the same spot where ever they are.
They'll move towards the source, then try move back to the path.

**Comment by Nevrdid** [comment]
Still not sure about if it will work ^^' but you may try to use reusePath opts in this moveTo : 
`moveTo(source.pos,{reusePath: 2})` as the default value is 5, just try to reduce it to 2 ( not sure if it will not cause cpu issue). Maybe reduce it only if previousRoom!=ActualRoom can avoid the possible expensive cost.

**Comment by TooAngel** [comment]
Currently I have on CPU problems creating this issue. If a tick is skipped and the creeps ends up in the other room.

Anyone else have this problems, out of other reasons?

**Comment by ikiris** [comment]
I've seen carries / roomers dance on borders recently. Usually adjacent to a room with path creation issues. The path ends up being along the border, and they fail to move away from the border before moving along it. I don't have any MMO world rooms experiencing this due to respawn however.

**Comment by samogot** [comment]
I think this is fixed already and could be closed

**Comment by TooAngel** [comment]
K, thx.

You can close the ticket with the commit, too. With `Fixes #157` (https://help.github.com/articles/closing-issues-via-commit-messages/)
