### ISSUE TITLE
No Path error

### ISSUE THREAD

**Issue by RobDaPraia** [TooAngel/screeps#187]
Noticed today that some of the creeps keep in the same spot complaining: No Path, see screenshot

![image](https://cloud.githubusercontent.com/assets/3207395/22521713/3934f5bc-e8b9-11e6-97b4-8ef29e966cf2.png)

**Comment by Nevrdid** [comment]
which role is it, which target have them ? you can see this in their memory.
Also you may join our slack channel, if you want to solve it easier :)

**Comment by RobDaPraia** [comment]
Sorry, when I woke up this morning they had died already. When it happens again I will let you know with the roles/targets fro memory. 

Will close this issue
