### ISSUE TITLE
Extractor Issue

### ISSUE THREAD

**Issue by totalschaden** [TooAngel/screeps#191]
Extractor seem to have a Problem when being on main path for Harvesting. Going back and forth, only harvest a few times.

http://i.imgur.com/eXLWqJx.gif

**Comment by TooAngel** [comment]
You can only harvest the extractor every 5 ticks. The gif looks like it should be. Or do I miss something?

http://support.screeps.com/hc/en-us/articles/207715739-StructureExtractor#cooldown

**Comment by totalschaden** [comment]
Didnt know that, gues its fine then. Closing
