### ISSUE TITLE
Blocking if reserver is on source path of external rooms.

### ISSUE THREAD

**Issue by Vanhal** [TooAngel/screeps#192]
The reserver sits on the path to one of the sources which causes the carryers and sourcers to get blocked up behind the reserver.
![image](https://cloud.githubusercontent.com/assets/7526890/22645765/8d3b895a-ec60-11e6-93c4-17f4b645985b.png)

**Comment by Nevrdid** [comment]
^^' bad room patern i think we should setup paths to be minium 2 case long. Will think about when i'll watch on. Dunno if there is an easy fixe so i supose the faster is to unclaim/respawn if you can ^^'

**Comment by Vanhal** [comment]
I looked around but How would i blacklist the room?

**Comment by Nevrdid** [comment]
https://github.com/TooAngel/screeps/blob/master/src/prototype_room_external.js#L316
`if (this.name === 'the room name' || this.memory.lastChecked !== un..... `

**Comment by TooAngel** [comment]
Problem still exist? Try out my workspace branch https://github.com/TooAngel/screeps/tree/workspace
