### ISSUE TITLE
Defense strategy/fillers

### ISSUE THREAD

**Issue by RobDaPraia** [TooAngel/screeps#194]
Hi,

I just noticed the following situation in my world under attack, maybe you can use this info to improve the scripts strategy.

My world is under attack but cannot defend: cannons are empty, only one fightRampa is effective, sources are not send through links because of missing fillers, have a look at the screenshots

A new storage filler creep spawned, but seems like it is doing nothing. Memory:

```
	storagefiller-127		{9}
	
role	:	storagefiller
	
number	:	127
	
step	:	0
	
base	:	W52S87
	
born	:	17324510
	
killPrevious	:	true
	
	routing		{5}
	
targetRoom	:	W52S87
	
targetId	:	filler
	
	route		[1]
	
	0		{1}
	
room	:	W52S87
	
routePos	:	0
	
pathPos	:	1
	
	_move		{4}
	
	dest		{3}
	
time	:	17324645
	
path	:	39232
	
room	:	W52S87
	
	last		{3}
	
	pos1		{3}
	
x	:	40
	
y	:	23
	
roomName	:	W52S87
	
	pos2		{3}
	
x	:	40
	
y	:	23
	
roomName	:	W52S87
	
	pos3		{3}
	
x	:	40
	
y	:	23
	
roomName	:	W52S87

```

![image](https://cloud.githubusercontent.com/assets/3207395/22802341/b9e0529e-ef10-11e6-827d-274959e160b4.png)
![image](https://cloud.githubusercontent.com/assets/3207395/22802347/bee04308-ef10-11e6-8229-5ce957016ce1.png)

![image](https://cloud.githubusercontent.com/assets/3207395/22802435/1a043744-ef11-11e6-8bf1-046828e8e655.png)

**Comment by RobDaPraia** [comment]
Update: another attacker just invaded my world, canons still empty.

Well, need some sleep now, will have a look at the situation tomorrow

![image](https://cloud.githubusercontent.com/assets/3207395/22803127/fa1e6dde-ef13-11e6-9bc2-fbdb01914bb4.png)

**Comment by RobDaPraia** [comment]
Well, this doesn't look good, will have to find a new world...

![image](https://cloud.githubusercontent.com/assets/3207395/22803186/3bbc3f78-ef14-11e6-92aa-9a0e64916086.png)

**Comment by RobDaPraia** [comment]
Maybe this can be useful info: they destroyed my world in 20 minutes with the following squad of 3 creeps
 
![image](https://cloud.githubusercontent.com/assets/3207395/22803351/dcf40358-ef14-11e6-8ac3-8e248d23d31b.png)

**Comment by TooAngel** [comment]
Thank you for the details description.

I just opened an enhancement issue #198 where we can start to discuss how we should design our defense.

**Comment by RobDaPraia** [comment]
Great.

I also noticed that the enemy creeps had a lot of healing and continuously moved into the room and outside the room for healing, so the fightRampa was never able to destroy those creeps.

**Comment by Pyrockk** [comment]
Im getting basically the same issue with storage fillers not filling the tower up
![image](https://user-images.githubusercontent.com/34846978/34774733-967649e2-f664-11e7-8cb8-ae0d1ebdd2ac.png)
