### ISSUE TITLE
Defense

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/screeps#198]
One tower is at the filler. The other towers are placed at the exits, next to links.

When under attack:
towerfiller are send out (currently not working) to the outter towers and transfer energy from the link to the tower.
The filler starts to distribute energy from the storage to the outer links.

After some threshold defender (melee and ranged) are spawned.

**Comment by TooAngel** [comment]
Discussion about the best defense strategy, current status will be updated in the description of this issue.

**Comment by TooAngel** [comment]
Well, will close this, discussion can be reopened if necessary.

**Comment by Pyrockk** [comment]
my filler is not filling up the tower returning codes "no directions"
