### ISSUE TITLE
undefined error in prototype_room_routing, mineral too close to exit?

### ISSUE THREAD

**Issue by mylemans** [TooAngel/screeps#211]
I got this error today:

Executing room failed: E81S4 TypeError: Cannot read property 'x' of undefined TypeError: Cannot read property 'x' of undefined
   at Room.updatePosition (prototype_room_routing:105:33)
   at buildCostMatrix (prototype_room_init:168:29)

The issue is most likely that the mineral is very close to the room' exit.

https://github.com/TooAngel/screeps/blob/master/src/prototype_room_routing.js#L105

**Comment by Nevrdid** [comment]
Can't try but i supose this should work better.

```
let nearPosGenerator = mineral.pos.findNearPosition();
let extractor = this.memory.position.creep[mineral.id] || nearPosGenerator.value();
while (!extractor) {
  extractor = nearPosGenerator.next().value();
}
```

**Comment by TooAngel** [comment]
Do you still have the error, there were some improvements on `updatePosition`.
