### ISSUE TITLE
Keep spawning harvester

### ISSUE THREAD

**Issue by heunghingwan** [TooAngel/screeps#212]
it seem inRoom function at prototype_room_creepbuilder.js have a bug

**Comment by Nevrdid** [comment]
More infos can help ^^' I haven't this issue so don't see where it can come from.
What is your IGN as i can see your rooms ? What is your queues? Can you log returns in creepbuilder functions ?

**Comment by Guss42** [comment]
same issue for me in room E82N28 (owner Guss)

**Comment by Nevrdid** [comment]
#216 should fix all

**Comment by Nevrdid** [comment]
or i believe just this : https://github.com/TooAngel/screeps/pull/216#discussion-diff-103112832R83
is enough

**Comment by Guss42** [comment]
will take a try, but funny to get near 20 harvester when controller get level 2 XD

**Comment by Nevrdid** [comment]
^^' you should remove your queue with `delete Memory.rooms[roomName].queue` and you can remove all harvester with 
```
forEach(Game.rooms[roomName].find(FIND_MY_CREEPS,{filter: s => s.memory.role === 'harvester'}), s => s.memory = undefined
```

**Comment by Guss42** [comment]
it's solved thanks for reply, I will now start to read and understand code and try to participate ^^

**Comment by Nevrdid** [comment]
yw :) you can join our slack channel.
