### ISSUE TITLE
Default pathing does not avoid trivial swamps

### ISSUE THREAD

**Issue by karlthepagan** [TooAngel/screeps#224]
https://screeps.com/a/#!/room/W29N15

harvester-676 took the path including points 20,15 and 20,16 - diagonal moves would avoid this.

Recommend a temporary costmatrix or fallback to default moveTo until roads are in place.

**Comment by TooAngel** [comment]
Well I think this only happens in the startup phase, roads should be build soonish, maybe a bit later if it is the first room.
Yes, could be improved, thanks for reporting. PR is welcomed :-)

**Comment by TooAngel** [comment]
When moving on path roads on swamps are build from the start, I think this solves this problem, too.
