### ISSUE TITLE
harvesters not going to dropped resource

### ISSUE THREAD

**Issue by theys1995** [TooAngel/screeps#233]
Is this intended ? All of the harvesters stand idly by that sourcer waiting to drop resource while there is 2500 in the bottom right corner dropped by a carry. This is happening for 300-500 ticks.
![screenshot from 2017-03-23 13-23-50](https://cloud.githubusercontent.com/assets/10806030/24245736/c2758e4c-0fcc-11e7-8f0e-ae7753e4d9dc.png)

**Comment by invisioblack** [comment]
They will eventually move to the other pile as they get full and wander over to build...  then they will start using the closer pile.

**Comment by TooAngel** [comment]
The decision of dropped energy is base on the distant and amount of energy. Maybe these factors can be improved.

I guess you are not in the situation anymore. I think this is one of the issues which can be improved while in the situation, but difficult to address later. Also the system works different RCL >= 4. Will close this.
