### ISSUE TITLE
layout pathing issue

### ISSUE THREAD

**Issue by ikiris** [TooAngel/screeps#235]
The below layout is problematic as far as routing goes. It creates deadlocks with harvesters primarily, but also scouts etc.

You can see an example deadlock below, due to the combination of the storagefiller and the extension blocking the side path out of the area, but the routing set up to ignore creeps.

I've tried to work around it, but I don't understand the base layout system enough to make any changes.

![Imgur](http://i.imgur.com/yEUqiwa.jpg)

**Comment by TooAngel** [comment]
Are you using the latest master TooAngel/updateposition merged, which fixed some base layout issues?

**Comment by ikiris** [comment]
Yeah it was on master.

**Comment by TooAngel** [comment]
Can you delete the Memory of the room so that the layout is recalculated? `delete Memory.rooms.ROOMNAME`

Besides that AFAIK there is an issue with the scout, I think the reason is that the scout sometimes doesn't ignore other creeps.

**Comment by ikiris** [comment]
Ive done that often to try to fix some stuck creeps. The scout thing i'm aware of in several different cases. It tries to path through static creeps and blocks everyone behind it.

**Comment by TooAngel** [comment]
Is this issue fixed? If not please test my workspace branch https://github.com/TooAngel/screeps/tree/workspace
