### ISSUE TITLE
getEnergy priority order - especially when moving only spawner

### ISSUE THREAD

**Issue by ikiris** [TooAngel/screeps#237]
Almost became screwed due to getEnergy prioritizing dropped harvest energy across the map instead of local storage when moving the spawner.

I think for efficiency's sake, as long as carries / links are operational, the first pass should be local dropped energy, then storage, then room dropped energy, ideally weighted due to path distance.

It should at minimum be overridden when moving the spawn to prefer storage

**Comment by TooAngel** [comment]
Sounds good. Especially energy prioritization. PR welcomed.

I don't think we should do a special case for the move spawn. Seems like it worked for you, I guess it was an exciting time watching your creeps and hope that they will make it ;-)
