### ISSUE TITLE
Memory.players not declared

### ISSUE THREAD

**Issue by Nevrdid** [TooAngel/screeps#24]
hi. tried your script and got an error about Memory.players when scout visited his first room. Just had to add players to memory and set it as object but it could be better if you initialise it somewhere :)

**Comment by TooAngel** [comment]
Thanks for reporting, do you still have the stacktrace?

**Comment by Nevrdid** [comment]
No. it's ok. Didn't pulled request because I don't understand all you're modules yet and I'm working on my IA today. :)

**Comment by TooAngel** [comment]
K. I thought just the message in the console, usually points out the position of the problem. Guess I will find out anyway.

Sorry for the code structure weren't focused good quality in the beginning and now I have the mess :-) How I can improve the in the next time or tying at least.
