### ISSUE TITLE
default creep pathing appears to deadlock

### ISSUE THREAD

**Issue by dmiddlecamp** [TooAngel/screeps#244]
I'm very new to this project / and just starting to explore the code.  I've checked in on my creeps a few times and found they're deadlocked in this configuration.  For whatever reason, maybe they're trying to move into eachother or something, they're locked in place and can't route themselves out of this situation.  Any advice?

<img width="713" alt="screen shot 2017-04-04 at 10 00 24 am" src="https://cloud.githubusercontent.com/assets/833793/24663431/83c29e42-191d-11e7-8ddd-93645db9d5c0.png">

**Comment by JetBalsa** [comment]
Ya, I have seen this before, we are working on some patches that if it detects a deadlock to just start moving outwards and then rotate them back into paths

**Comment by TooAngel** [comment]
We improved a lot in this direction within the last commits. Will close the issue, if you still experience the problem, please reopen.

**Comment by 0xF6** [comment]
![image](https://user-images.githubusercontent.com/13326808/29684109-694713f6-8919-11e7-8bdf-bad4f884c7e8.png)
![image](https://user-images.githubusercontent.com/13326808/29684318-30236114-891a-11e7-96ce-7c80c92b07b5.png)
