### ISSUE TITLE
Most screeps are not getting respawned

### ISSUE THREAD

**Issue by labrown** [TooAngel/screeps#245]
I'm new to screeps and the TooAngel code base.

I'm running TooAngel commit 93e460e7f7 and seeing problems with a GCL 1 account in a new spawn (RCL1).  Once harvesters and planers, carriers, and repairers (I think) are spawned the first time, they never get respawned.  Sourcers continue to be spawned but eventually the room gets into a state where it can't spawn a the larger sourcer it wants and everything stalls out and decays.

When I look at the rooms 'roles' array I see:
JSON.stringify(Memory.rooms['W8N3'].roles)
 {"harvester":true,"sourcer":false,"planer":false,"carry":true,"repairer":true}

If I set harvester to false, then a group of harvesters is spawned and roles['harvester'] is set back to true.  Once that set dies, no more harvesters are spawned.  I can do the same with repairers, planers, and carry.

Something isnt' setting the room's roles[ROLE] variable back to false when it should, but I don't understand the code base well enough to figure it out where yet.

**Comment by Brutalbic** [comment]
I'm having the same issue as well on a private server, it happens shortly after you reach RCL 4, then only a few sourcers and repairers get respawned, then the room decays all the way back to RCL 1 before anything spawns again.

Been doing the same as you and spawning in a few harvesters manually just to keep my room from going all the way back to RCL 1 again.

**Comment by labrown** [comment]
I've got a ludged hack that prevents this problem from occurring but am not sure it's a fix as I don't fully understand the logic of the code involved.

**Comment by JetBalsa** [comment]
Whats the patch?

**Comment by labrown** [comment]
See PR #248 for the fix I found to this problem.
