### ISSUE TITLE
Creeps stuck on path

### ISSUE THREAD

**Issue by Nevrdid** [TooAngel/screeps#28]
![creeps_stuck](https://cloud.githubusercontent.com/assets/13476270/21326173/c74279a4-c629-11e6-805e-a95583031fa7.png)

These road block all creeps if they are some. The 4 creeps on the top always switch pos but the 2 on the bottom-right never move.
W71S66  on official serv for see them.

**Comment by TooAngel** [comment]
I guess the issue has been fixed by now? Did some changes about the pathfinding with a misplacedSpawn.
I guess it is hard to reproduce, I would suggest to close the ticket.

**Comment by Nevrdid** [comment]
yeah, looks like they finally found a way :)  but dunno if it's fixed. all way we could open a new one if someone got it again.
