### ISSUE TITLE
Retaliation factor

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/screeps#29]
Currently only hostile actions are counted into the idiot counter.

Introducing a retaliation factor for actions of the bot could reduce the constant growing of idiots.

E.g. factor of 0.1
If a hostile creeps is in my room idiot +1, if my creep is in hostile room idiot -0.1
Same for destroyed rooms and nukes

**Comment by mschultheiss83** [comment]
and what about idiot is healing my creeeps? is idiot od friend?

**Comment by TooAngel** [comment]
I think it is a bit hard to find out who healed you. We could do something like, if a creep is healed and not from ourself, we decrease the idiot counter for all creeps in the room. (This would be a bit odd if you are attacking a room with someone else together, ...). We can try.

**Comment by mschultheiss83** [comment]
please open feature branch, would like to put some thoughts in it

**Comment by TooAngel** [comment]
> please open feature branch, would like to put some thoughts in it

Code? Or Ideas? I want to open issues for the different topics (like this one) so that we can start to discuss and formulate the ideas better. So that everyone can pickup a feature and implement it. Sounds good, sounds bad, I don't mind?

**Comment by TooAngel** [comment]
I migrated `idiot` to `reputation`.
- Hostile actions reduced the `reputation`
- Sending resources or solving quests increase the `reputation`
I think this is a nice step for now, will close this issue in the next PR and open a new one as soon as new ideas come up.
