### ISSUE TITLE
Include incoming nukes in idiot counter

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/screeps#30]
credits worth of 100k ghodium?

**Comment by Somotaw** [comment]
not sure I understand what you're going for? :)

**Comment by TooAngel** [comment]
Currently incoming nukes are not considered in the idiot counter. If someone drops a nuke on your room the idiot counter should be increased.
The current idea is to be able to reduce the idiot counter by sending resources, so I would consider the idiot value as credits.
Instead of having fixed values for specific actions I think it is good (funny) to bind it to specific costs, e.g.
Destroying the last spawn of a room is worth: 1 subscription token (get the highest price from the market and add this to the idiot counter)
Dropping a nuke could be worth: 100k ghodium (take the price form the market and add it to the idiot counter).

Makes more sense?

**Comment by TooAngel** [comment]
This is already implemented, will close in the next pr
