### ISSUE TITLE
layout issues

### ISSUE THREAD

**Issue by mschultheiss83** [TooAngel/screeps#349]
First since my last layout (Version 14) room E69N38 got better

![screeps e69n38](https://user-images.githubusercontent.com/2712470/29211470-8c509280-7e99-11e7-98ad-2da618b97915.png)
in V14 this path was blocked, now my spawns will be recreated near controller, and if path is blocked creeps have to move around to main path (start -> nuker)

but as shown in room E74N39 many creeps will not spwn on path (loosing ticks to reaching the path, without road)
![screeps e74n39](https://user-images.githubusercontent.com/2712470/29211472-8c5b8802-7e99-11e7-91cf-cf881795cb1f.png)

and same in E79N38, but even more worse
![screeps e79n38](https://user-images.githubusercontent.com/2712470/29211471-8c575a7a-7e99-11e7-8f1a-557f300a852d.png)
creeps have no change to get to the main path

**Comment by mschultheiss83** [comment]
adding walls to the layer was my only idea, 
check for each spawn if there is a Adjacent position were creeps have no route to terminal/storage/sources

**Comment by mschultheiss83** [comment]
or maybe adding every 8-10 extensions a space

**Comment by samogot** [comment]
I think the easiest way would be to add all valid positions (`findNearPosition`) around spawns as walls. we can do it in the end, after room layout is complete. A bit tricky part is to do something to not repair that walls

**Comment by mschultheiss83** [comment]
> A bit tricky part is to do something to not repair that walls
dont think so, just need to change from closest target to a "target-list" filtered by coords (x <=2 || x >=47) and (y <=2 || y >=47)

**Comment by samogot** [comment]
but there plans for several layers of wall. I think that the better way is not to check by position, but save spawn's wall into different memory property, so we can check them in `Room.prototype.destroyStructure` but filter out in repairer logic

**Comment by TooAngel** [comment]
> A bit tricky part is to do something to not repair that walls

I'm not sure if this is really a problem, the walls should be reachable from the path, due to distance <= 3. It is a bit off energy, but not so much. So IMHO don't care until it is a problem

**Comment by mschultheiss83** [comment]
we talk about maximum 7 additional walls, at all my rooms we talk about an everage of 2,9 walls

so 
- so a plus 3 walls dont hurt, if the walls are at equal hits level, eg for a new room
- if not, it takes a long time to raise, and in the mean while the repairer stays still, because of random (not on path)

**Comment by TooAngel** [comment]
If the repairer is not on the path it doesn't matter and shouldn't block anything (I still think it also moves random when not on the path, but I'm not sure). If the repairer is on the path it should move random, so no problem.

**Comment by TooAngel** [comment]
So I agree for build up rooms it is some kind of an issue, but only temporary and not a big one

**Comment by TooAngel** [comment]
We build now walls at wrong spawn exits.
