### ISSUE TITLE
Autoattack level 2

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/screeps#35]
To be able to kill simple bots with `GCL >= 3` and a tower, heal creeps need to be send.
The idea:
 - Send a dismantler
 - Send three heal creeps
 - dismantler waits in the room before `targetRoom`
 - Heal creeps enter `targetRoom`, heal themself, and switch on the room border until the tower is drained

**Comment by mschultheiss83** [comment]
@TooAngel maybe you could add some docs for usage?
eg: more details in 
```brain.startSquad(baseRoomName, targetRoomName)``` https://github.com/TooAngel/screeps/blob/master/src/config_brain_squadmanager.js#L98
```brain.handleSquadmanager``` https://github.com/TooAngel/screeps/blob/master/src/config_brain_squadmanager.js#L73

**Comment by TooAngel** [comment]
Was not necessary meant to be called manually, but thanks for the hint, will add.

**Comment by WhiteHalmos** [comment]
+1 for automatic rather than manual.

**Comment by mschultheiss83** [comment]
sure automatic! 
we need to add some lines to creeps in externalRooms, 
if they see invaders or other hostile players, they should start a squad spawn

started working on this in #68

**Comment by TooAngel** [comment]
I thinks this we be solved by #140
