### ISSUE TITLE
Improve code structure

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/screeps#36]
Many for loops can be replace by lodash filter.

Checks for structures can be replaced by tables:
```
     let hostileStructures = creep.room.find(FIND_HOSTILE_STRUCTURES, {
        filter: function(object) {
          let table = {
            [STRUCTURE_RAMPART]: true,
            [STRUCTURE_EXTRACTOR]: true,
            [STRUCTURE_WALL]: true,
            [STRUCTURE_CONTROLLER]: true
          };
          return !table[object.structureType];
        }
      });
```

**Comment by WhiteHalmos** [comment]
I like these tables, quite clear.

**Comment by Nevrdid** [comment]
thinking about better structure ... 
`
let hostileStructures = creep.room.find(FIND_HOSTILE_STRUCTURES, { 
  filter: struct=> _.include([STRUCTURE_RAMPART,
                                      STRUCTURE_EXTRACTOR,
                                      STRUCTURE_WALL,
                                      STRUCTURE_CONTROLLER], struct.structureType)
});
`

**Comment by mschultheiss83** [comment]
and go a bit further by move these arrays to
```roles.[role].HOSTILE_STRUCTURES``` or to 
```global.config.HOSTILE_STRUCTURES```

**Comment by Nevrdid** [comment]
yep, i can add it with roles.[role].settings. will check that.

**Comment by TooAngel** [comment]
I started with something like this some time ago: https://github.com/TooAngel/screeps/blob/master/src/prototype_room_cached.js

I don't think it is good to bind it to the room object, better to store in a global variable. In my cases I wanted it refreshed on each tick. I think we need to check how often it needs to be refreshed.

**Comment by TooAngel** [comment]
I think we have some kind of solution with the find abstractions.
