### ISSUE TITLE
Sources stack and not go to source and just repeat "R:p-1: 6"

### ISSUE THREAD

**Issue by Mordorreal** [TooAngel/screeps#365]
All other creeps also stop any activities. Current master, new player, one room.

**Comment by TooAngel** [comment]
Is the room on a public server? pic or it didn't happen :-)

https://github.com/TooAngel/screeps/blob/55f3347c46bc05c5b6cd8d6e0123c7a1704184c6/src/prototype_creep_routing.js#L248
The creep is not on the path and can't find a way to the path.
Is the creep spawned in a wrong direction from the spawn?

**Comment by Mordorreal** [comment]
Shard-0, Forgot to take pic. I'll do it late. The creep spawned as usual on top of the spawn. 
I found this part of code, but it's looks too complicated to understand logic in 10 min.

**Comment by TooAngel** [comment]
:-) K, when looking into, improve it for better readability ;-)

Room name?

**Comment by Mordorreal** [comment]
<img width="1440" alt="2017-08-18 23 18 40" src="https://user-images.githubusercontent.com/8039537/29476238-b6d81802-846b-11e7-8374-7548e9580339.png">
W18S97

**Comment by TooAngel** [comment]
Looks good. Does the message appear only for a couple of ticks?

**Comment by Mordorreal** [comment]
I waited for about 30 min and saw this message and all creeps stopped.

**Comment by TooAngel** [comment]
Let me know, when it happens again. (Maybe I'm available :-))

**Comment by Mordorreal** [comment]
<img width="1440" alt="2017-08-20 12 03 38" src="https://user-images.githubusercontent.com/8039537/29493485-aaf20ca2-859f-11e7-9d9f-89f8d6bcb881.png">
I still can't find reason yet.

**Comment by TooAngel** [comment]
Just ran into that issue, too. I'm currently testing: https://github.com/TooAngel/screeps/commit/f992867c7e4d5af4800e9a9180f4bd62b2a9f39f#diff-c8d523a1ce20222836a3218c4e14ec16
as changeset. Using our `moveToMy` instead of the `moveTo`

**Comment by Mordorreal** [comment]
Looks like all carriers start to moving but one sourcer stopped near base.
<img width="1440" alt="2017-08-20 12 26 16" src="https://user-images.githubusercontent.com/8039537/29493642-f5a0de60-85a2-11e7-8801-e1892d5289ab.png">

**Comment by TooAngel** [comment]
https://github.com/TooAngel/screeps/commit/e237e4bb5528c0f8afc70314e6bebe61c148003f#diff-c8d523a1ce20222836a3218c4e14ec16

**Comment by Mordorreal** [comment]
<img width="1440" alt="2017-08-20 12 47 33" src="https://user-images.githubusercontent.com/8039537/29493780-c3cea324-85a5-11e7-9d90-162729536ef5.png">
I killed old one and new one still stay at base.

**Comment by Mordorreal** [comment]
Now all sourcers stopped at base. 
<img width="1440" alt="2017-08-20 13 25 33" src="https://user-images.githubusercontent.com/8039537/29494048-1a963924-85ab-11e7-83ef-f3327769a1ff.png">

**Comment by TooAngel** [comment]
Hm, ok, then do not apply the patch :-)

**Comment by TooAngel** [comment]
I guess the problem will solve itself as soon as the spawn is moved to the correct position.

You could try the workspace branch if the problem is solved there,

**Comment by Mordorreal** [comment]
Ok. How it will be performed? How I can figure correct spawn position?

**Comment by TooAngel** [comment]
On RCL 4, storage.energy > 20000, `planer` creeps are spawned. The old spawn is destroyed, a new construction site is placed and build up.
!! The message 'You lost your last spawn' will appear, don't click on 'respawn'

It is not so easy to get the correct spawn position.

**Comment by Mordorreal** [comment]
Problem solved by moving spawn, but I think this is still issue.
