### ISSUE TITLE
All break issue.

### ISSUE THREAD

**Issue by Nevrdid** [TooAngel/screeps#37]
hey, come back this evening with only 2 creeps still alive. they are harvesters spaming "tr:incomplet" (proto_creep_ressources l 890)  I'll try to understand what happen and say you if i sucefully fix it.
room w72n71

**Comment by TooAngel** [comment]
First suggestion:

`﻿⁠⁠⁠⁠creep.moveTo(target.pos); return true;
`﻿⁠⁠⁠⁠delete Memory.rooms`

Maybe as workaround.

**Comment by TooAngel** [comment]
I guess the issue is that the creep can't find a complete path, using the structure positions from the room memory.
I think it needs to be investigated which is the target and what is blocking this path. Not sure how this can happen.

**Comment by TooAngel** [comment]
https://github.com/TooAngel/screeps/blob/master/src/prototype_creep_resources.js#L890

**Comment by Nevrdid** [comment]
Thanks, problem solve, looks my harvesters gonna launch back all.

**Comment by TooAngel** [comment]
You you mind sending a PR? Adding `Fixed #37` to the commit message?

**Comment by Nevrdid** [comment]
yeah, gonna do some PR tomorow :) coming back at my home this evening.

**Comment by mschultheiss83** [comment]
6 days later, nothing?
