### ISSUE TITLE
Request logic

### ISSUE THREAD

**Issue by 0xF6** [TooAngel/screeps#413]
1. Tower's have to attack the enemy creep that has body heal
2. After level `n+` controller will need to install rampart to spawn, storage and anything else.
3. When attacking  enemy creep of the measure, if not enough power towers, then start to repair rampart(spawn)
4. If spawn started attacking, activate safe-mode
5. Towers should attack one enemy creep at same time

**Comment by 0xF6** [comment]
6. If spawn was destroyed, to throw all the forces to build a new spawn

**Comment by TooAngel** [comment]
Well, there are a lot of ways how to improve the defense logic. These could be some points. I like activating the safe-mode when close to spawn.
I don't think it makes sense to throw any forces to rebuild the spawn, while under attack. If the last spawn is fallen usually this fight is over and the revive room drops in.

**Comment by 0xF6** [comment]
>I don't think it makes sense to throw any forces to rebuild the spawn, while under attack.
When the attack ends, it makes sense to return Spawn 🤔 
Especially when a player has only one room.

**Comment by 0xF6** [comment]
>Changelog (http://blog.screeps.com/2017/09/changelog-2017-09-19/)

>Safe mode activation is not possible when the controller is downgraded for 5000 or more ticks.

Hmm

**Comment by 0xF6** [comment]
Well.. 
This code copes with their tasks on private servers. and this current logic is not really needed~
