### ISSUE TITLE
Move layout center farther from Controller

### ISSUE THREAD

**Issue by sparr** [TooAngel/screeps#437]
sparr [Yesterday at 10:35 PM] 
in #angels_public
@tooangel layout question... why does the upgrader need to be adjacent to the controller?

tooangel [10 hours ago] 
When screeps was released, the upgrading creep needed to be adjacent to the controller, that was changed ~a year later, I never (had to) adapt

nevrdid [2 hours ago] 
approve tryto find better one. never looked at too. The same way, we may use multiple ones if we have enouth energy for them

sparr [< 1 minute ago] 
I just want to get away from walls to have fewer traffic jams. I'll think on how to choose the most open area to start the layout in

**Comment by sparr** [comment]
https://github.com/tedivm/ScreepsAutoSpawner/blob/master/autospawner/spawner.py#L281-L316

This (python) function calculates how far every tile in the room is from a wall. I am probably going to implement this as part of the room layout function, and then use openness score as the primary factor in deciding where to put the upgrader/storage, then use it as a tie breaker in the getBestNearPosition() calls for the other placements. This should produce layouts much less jammed up against walls.

This will obsolete PR #432

**Comment by samogot** [comment]
Upgrader near to controller is also useful because it can update controller sign

**Comment by sparr** [comment]
😢
That's a good point, thanks for pointing it out. I will account for that in whatever code I write for this.

**Comment by sparr** [comment]
At minimum, I'm going to implement that function as a tie breaker for getBestNearPosition.

**Comment by sparr** [comment]
There is some discussion of upgrader placement failures in #459 which I am attempting to redirect here.
