### ISSUE TITLE
Duplicate repairer

### ISSUE THREAD

**Issue by WhiteHalmos** [TooAngel/screeps#46]
There are often two repairers in the room at the same time: https://screeps.com/a/#!/room/E28S79

Even though there should be at most 1.

**Comment by Somotaw** [comment]
Is this fixed?

**Comment by WhiteHalmos** [comment]
Unfortunately not, I've still seen dups.

**Comment by invisioblack** [comment]
when you look at the repairer role - it's max of role value is 2.

**Comment by WhiteHalmos** [comment]
@invisioblack link to code?

**Comment by invisioblack** [comment]
the code I am using had a call with 2 on line 42. however in the repo it has a call with a 1,  

in any event I have noticed doubles occasionally when the spawn pops out because of the ttl offset.

**Comment by invisioblack** [comment]
So watching the AI run - I noticed that when a repairer accidentally wanders out of the room we spawn another one.  This is probably how we get 2.

**Comment by TooAngel** [comment]
There were a couple of changes in between. Will close it now, if it still occurs reopen it.
