### ISSUE TITLE
Traffic jams

### ISSUE THREAD

**Issue by Pyrockk** [TooAngel/screeps#496]
https://i.imgur.com/fRQuhLW.png
Constantly getting this happening. It seems to be the placement of the extensions?

It has resulted a few times in all the creeps deaths, which only allows low level harvesters to be spawned, and since the sources are a little far away it takes way too long for this harvester to deliver resources to extensions. So its a never ending loop of low level harvester production. Luckily this is my second room so i can send in creeps to help it, but the traffic jams continually occur and hamper the rooms progress

**Comment by Pyrockk** [comment]
I have abandoned the room. It seems to have been the tight spaces that this room had.

**Comment by TooAngel** [comment]
Well, I guess the issue is not existent in that form anymore, the linked PR will close the issue.
