### ISSUE TITLE
Pathing problem

### ISSUE THREAD

**Issue by orby2002** [TooAngel/screeps#497]
Hi I've been having a problem with my creeps getting stuck while trying to move into the next room to harvest the energy there. I don't know how to fix it. Please help. There are usually more waiting in line on the road into the second not sure why there are only 4 waiting at the time of the screen shot. but they will wait there until they die.

![screeps1](https://user-images.githubusercontent.com/31328550/35284848-789fae88-0021-11e8-8782-e446991a0d99.PNG)
![screeps2](https://user-images.githubusercontent.com/31328550/35284849-78b7cb8a-0021-11e8-9d3d-c860baa0a7cd.PNG)

**Comment by TooAngel** [comment]
#564 Introduces a couple of improvements on carries, I couldn't reproduce the behavior.
