### ISSUE TITLE
Error: Unknown module 'creep_upgrader'

### ISSUE THREAD

**Issue by abeltensor** [TooAngel/screeps#5]
When starting a new room, nothing happens unless I comment out the prepareMemory function. 
Here is the full error:

Error: Unknown module 'creep_upgrader'
    at Object.brain.prepareMemory (config_brain_memory:66:20)
    at main (main:18:9)
    at Object.module.exports.loop (main:44:5)
    at __mainLoop:1:52

Im only GCL 1, i get the feeling that lack of CPU power has something to do with this.

**Comment by TooAngel** [comment]
It seems like it is a Memory issue. I guess you had a creep before with the role 'upgrader'. The `config_brain_memory` module tries to load the creep role specific module combined from the role `creep_upgrader` which is not present. I would suggest to execute `delete Memory.creeps`.

**Comment by abeltensor** [comment]
That seemed to work and also fix the problem I had in the simulation after my controller reached level 2
