### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by pacomms** [TooAngel/screeps#553]
When i have installed this on new server and run and spawned a bot, the spawn appears but nothing else happens no creeps spawn nothing ? help

**Comment by HuggableShark** [comment]
Same thing happened after I spawned it on my dedicated server as well. If there is any data I can grab to assist with troubleshooting this feel free to let me know.

**Comment by TooAngel** [comment]
Hey, the easiest to debug is to run the code as your own player so that you can see the log output.

Are you using a default local server room or did you create a new map. If it is a default room, tell me the room name and I can have a look, too.

**Comment by HuggableShark** [comment]
Default dedicated server map, room W7N4 was where it failed on mine.

**Comment by TooAngel** [comment]
I tested W7N4 now and fixed the issues, when the Pull Request gets merged, it should be fixed, Feedback is appreciated.
