### ISSUE TITLE
Harvester problem with only 300 energy in room on higher RCL

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/screeps#585]
It seems that there is an issue with harvesters: https://github.com/TooAngel/screeps/pull/581#discussion_r464626547

The best approach would be to write tests for different cases and see when it fails. Any other solution is fine, too :-)

**Comment by Kill4Free** [comment]
The problem persisted with the last commits fix. I added some logging and found the real problem!
I will add a pull request if I've verified the problem now.

**Comment by TooAngel** [comment]
I added the first unit test for the harvester config: https://github.com/TooAngel/screeps/blob/69fa5a754d6f4c0e14b6627a7c0154ad96b836bc/test/test.js
Its part of the pull request: https://github.com/TooAngel/screeps/pull/588

Maybe this helps to debug it easier, or at least prevent such issues in the future.

**Comment by Kill4Free** [comment]
For clarification: lodash merge alters the first object. This lead to the bug.
