### ISSUE TITLE
Harvesters bug

### ISSUE THREAD

**Issue by Kill4Free** [TooAngel/screeps#597]
Since #587 I have a problem where I'm getting multiple harvesters spawned (around 20 per room).
The other problem is the harvesters aren't putting any effort into refilling the spawn/extensions instead they're upgrading the controller, repairing walls etc.
I think it's just another symptom so much harvesters because only the first has `transferEnergy` task see [here](https://github.com/TooAngel/screeps/blob/9655ecaf71bce354628723d12f1d7388c75f9b4f/src/prototype_creep_resources.js#L18).

**Comment by TooAngel** [comment]
Yeah, I recognized the error some days ago. #593 should fix it.

**Comment by Kill4Free** [comment]
Okay just checked d7efd65dbca628a1c4feef5e44c54973247c5655 is working fine.
