### ISSUE TITLE
Stats => Grafana

### ISSUE THREAD

**Issue by TooAngel** [TooAngel/screeps#61]
The discussion came up about a shared Grafana dashboard for all TooAngel AIs.

Current approach:
Use https://github.com/ScreepsPlus/node-agent to send to screepspl.us

If someone would like to join ping me or @Nevrdid

**Comment by TooAngel** [comment]
semperrabbit provided some ingame code:

```
global.agentTest = function(){//*
    var statsDataJSON = JSON.stringify(Memory.stats)
    var passToken = Memory.screepsplusToken;
    var output = `<SCRIPT>
if(!document.ticks)document.ticks={}
if(document.ticks['t${Game.time}']===undefined){
 document.ticks['t${Game.time}']=true
 var x=new XMLHttpRequest()
 x.open("POST", "https://screepspl.us/api/stats/submit", true)
 x.setRequestHeader("Authorization","JWT " + "${passToken}")
 x.setRequestHeader("Content-Type", "application/json;charset=UTF-8")
 x.onreadystatechange=function(){if(x.readyState===XMLHttpRequest.DONE&&x.status===200){console.log('resp',x.responseText);}}
 x.send(JSON.stringify(${statsDataJSON}))
}
</SCRIPT>`
    console.log(output.split('\n').join(';'));
//*/
}
```

@Nevrdid maybe you like to have a look, this could work without agent and maybe two config switches, one for `stats` and one for `directSend`. What do you think?

**Comment by WhiteHalmos** [comment]
Happy to share data as long as it's easy and secure. :)

**Comment by TooAngel** [comment]
Small motivation to join. When I see your rooms in the dashboard I will have a look if I find unusual stats :-)

**Comment by TooAngel** [comment]
I think it would be good to have some information in the READMD / docs. If this is done we can close the issue.

@Nevrdid would you mind?

**Comment by mschultheiss83** [comment]
i like to join

**Comment by TooAngel** [comment]
@mschultheiss83 The necessary information is in the https://github.com/TooAngel/screeps/blob/master/config_local.js.example

I want to make the credentials even more public by putting them in the README. My plan for the TooAngel account is to have them as public as possible, just FYI.
If you like to have graphs you can register on screepspl.us if you don't mind having you graphs public, just use this account.

**Comment by mschultheiss83** [comment]
https://github.com/TooAngel/screeps/pull/361
