### ISSUE TITLE
TypeError: Cannot redefine property

### ISSUE THREAD

**Issue by UndefinedCpp** [TooAngel/screeps#643]
I got a few problems running the scripts. The console output is like the following:
```
[Time] TypeError: Cannot redefine property: data
                  at Function.defineProperty (<anonymous>)
                  at prototype_room:6:8
                  at eval:108:4
                  at Object.<anonymous>:2:206408
                  at require:19:1
                  at eval:71:4
                  at Object.<anonymous>:2:206408
```
It occurs in: ```prototype_creep``` and ```prototype_room``` as far as I know.
Can anybody help me ?
Sorry my English is not so good.

**Comment by TooAngel** [comment]
I can try to help.
Where are you getting the error on the public or on the private server?

I'm guessing you are just trying to execute the script. The repository is meant to be used within the https://screeps.com/ server environment.

**Comment by UndefinedCpp** [comment]
I was trying to run in simulation mode... and I guess that was the point. Thanks for help.
