### ISSUE TITLE
Nextroomers not using both sources

### ISSUE THREAD

**Issue by WhiteHalmos** [TooAngel/screeps#65]
They bunch up and only use one source, blocking each other.

**Comment by TooAngel** [comment]
That is correct :-)

AFAIK on GCL 2 this is a problem. Nextroomers have some logic if the room is underSiege to select a source.
Usually on a higher GCL the nextroomers are bigger and clean out a source in ~150 ticks, so they still only harvest one source each time, switch to the other as soon as the first is depleted. But still are able to get all energy out of the sources.

Still open for improvement.

**Comment by WhiteHalmos** [comment]
Great! I'll fix this when I get around to it. :)

**Comment by mschultheiss83** [comment]
**HINT**
see `Memory.rooms['roomName'].sources_index` in sourcer

**Comment by TooAngel** [comment]
> HINT
> see Memory.rooms['roomName'].sources_index in sourcer

I think I removed that, was deprecated, but you can find it in the git history. This could be an approach.

**Comment by WhiteHalmos** [comment]
Actually I'll leave it to someone else, feel free to take this bug. :)
