### ISSUE TITLE
[LOGIC REFINE] withdraw energy from Tombstone and Ruin

### ISSUE THREAD

**Issue by XenoAmess** [TooAngel/screeps#666]

**Comment by mschultheiss83** [comment]
withdraw Tombstone is implemented, see https://github.com/TooAngel/screeps/blob/master/src/prototype_creep_resources.js#L120

```js
Creep.prototype.withdrawTombstone = function(onlyEnergy) {
```

add them up into `Creep.prototype.pickupEnergy`
