### ISSUE TITLE
[LOGIC REFINE] suggest spawn creeps at TOP, but not force it.

### ISSUE THREAD

**Issue by XenoAmess** [TooAngel/screeps#674]
is there any reason to force the position we spawn creeps at top?
I do wonder because sometimes when I get severe stuck, I think maybe it be better for sometime allow it spawn from other sides
any ideas?

**Comment by XenoAmess** [comment]
Well I did a change commit about it and during one whole day in 4 rooms, I don't see it make any trouble. think should pr it here.

**Comment by XenoAmess** [comment]
also agreed by @mschultheiss83 in discord, so I think we can try it at least..

**Comment by mschultheiss83** [comment]
sure, let's test

**Comment by TooAngel** [comment]
The planing of the base puts spawns below (bottom) of the path. That is the reason that it always spawns to the top.
Without this it can happen, that the creep will be on a position which can not reach the main path, because the extensions are blocking the way.
