### ISSUE TITLE
feature/Add screeps-visual and make visualizer manager object

### ISSUE THREAD

**Issue by Somotaw** [TooAngel/screeps#80]
- for visualizing different paths or other stuff
when I did this it also showed routes that look way off, perhaps routing needs some work? :)

**Comment by Somotaw** [comment]
got this done, but I cannot create pull requests so i'll just link it here.
https://github.com/Somotaw/screeps

**Comment by WhiteHalmos** [comment]
Pictures please? I don't have screeps-visual. :)

**Comment by Somotaw** [comment]
![image](https://cloud.githubusercontent.com/assets/6491698/21599438/cda4e4c8-d16c-11e6-88f8-2745f918e6a3.png)

**Comment by Somotaw** [comment]
also try the fork and you do ;)

**Comment by Somotaw** [comment]
whoever made visual.js needs to work on their === and ; XD

**Comment by Somotaw** [comment]
maybe this is cause for cpu hog?

**Comment by Somotaw** [comment]
![image](https://cloud.githubusercontent.com/assets/6491698/21600407/f80dd2c4-d17b-11e6-8b2f-e863aea7cf02.png)
res is path's for creeps and while is for rooms in my setup

**Comment by TooAngel** [comment]
I think it is an issue with the screeps-visual. Most of the creeps only move on the pre calculated paths, if they were off the creeps were stuck at the walls and not try to find another way.

As always, I could be wrong ;-)

**Comment by TooAngel** [comment]
> maybe this pathing is the cause of the crazy cpu im getting testing this ^^

Not sure if you already recognize the screeps-profiler integration, I think this is good for debugging the CPU issues.

**Comment by Somotaw** [comment]
Will test the current function in a controlled enviroment and come back with definite answers.

Yes I've been using screeps-profiler alot, great tool :)

**Comment by Somotaw** [comment]
Fixed som stuff on local branch, the deviant lines in my example are based off direct room memory, once I used the getMemoryPaths all the roompaths now look ok :)

**Comment by Somotaw** [comment]
![image](https://cloud.githubusercontent.com/assets/6491698/21645444/465afed6-d292-11e6-851c-8ab3da0431b8.png)

**Comment by Somotaw** [comment]
starts to look pretty good eand easy to visualize building layout and pathfinding for squads with this :D

**Comment by TooAngel** [comment]
The implementation looks promising.
What is currently missing from my perspective is some kind of documentation.
Like:
 - Which browser script do I need to install
 - How to enable
 - What are the config flags


Also some gut feeling about the creep path. A creep stores paths of `moveTo`, maybe these are stored in `_move`. If the creeps move by `move`, the position changes, but the path in `_move` stays the same - Some parts are through walls. Didn't check, but this could be an explanation.

**Comment by Somotaw** [comment]
Yes, also thinking about including future buildings as circles, something similar to this 

![](https://files.slack.com/files-pri/T0HJCPP9T-F3PBMK206/tmp.png)

**Comment by Somotaw** [comment]
Would having different colors for different creep roles using paths be of any use?

**Comment by TooAngel** [comment]
I like the building idea, different colors for different buildings would be nice.
extension = yellow
powerSpawn = red
...

**Comment by Somotaw** [comment]
#135

**Comment by Somotaw** [comment]
![image](https://cloud.githubusercontent.com/assets/6491698/21927057/c924b6a6-d984-11e6-9c6a-ee4584dec0be.png)

**Comment by TooAngel** [comment]
Good work

Can we add some information about it in the README? How to enable, what it does, screenshots would be awesome.
Maybe also in the list of features?

**Comment by Somotaw** [comment]
Aye after I finish logic for squads 🙂
