### ISSUE TITLE
Pathing through Keeper in attack range

### ISSUE THREAD

**Issue by totalschaden** [TooAngel/screeps#94]
Creeps are currently pathing through Keepers attack range and get attacked.

2 examples with visualizer:

http://i.imgur.com/wS06lRN.jpg
http://i.imgur.com/zHsXNkH.jpg

**Comment by TooAngel** [comment]
Especially http://i.imgur.com/zHsXNkH.jpg is tricky to fix. The routing always connects the rooms with the 'middle' exit. Before changing, this would need to be discussed extensively.

We can try to avoid the Source Keepers by increasing the values in the costMatrix around Source Keepers, range 3.

But in the end I think the best would be to enable and fix Source Keeper mining again => More energy, no source keepers.

**Comment by TooAngel** [comment]
AFAIK this has been fixed.
